return {
  -- "utilyre/barbecue.nvim",
  -- name = "barbecue",
  -- version = "*",
  -- dependencies = {
  --   "SmiteshP/nvim-navic",
  --   "nvim-tree/nvim-web-devicons"
  -- },
  -- opts = {
  --   show_dirname = false,
  --   show_modified = true,
  --
  --   -- show_basename = false,
  --   kinds = {
  --     File = "",
  --     Module = "",
  --     Namespace = "",
  --     Package = "",
  --     Class = "",
  --     Method = "",
  --     Property = "",
  --     Field = "",
  --     Constructor = "",
  --     Enum = "",
  --     Interface = "",
  --     Function = "",
  --     Variable = "",
  --     Constant = "",
  --     String = "",
  --     Number = "",
  --     Boolean = "",
  --     Array = "",
  --     Object = "",
  --     Key = "",
  --     Null = "",
  --     EnumMember = "",
  --     Struct = "",
  --     Event = "",
  --     Operator = "",
  --     TypeParameter = "",
  --   },
  --
  -- },
  -- config = function()
  --   require("barbecue").setup({
  --     attach_navic = true,
  --     -- create_autocmd = true,
  --   exclude_buftypes = { "toggleterm", "Trouble", "netrw", "oil" },
  --   exclude_filetypes = { "lua" },
  --
  --   })
  -- end
}
