return {
  -- "nvimdev/lspsaga.nvim",
  -- dependencies = {
  --   "nvim-treesitter/nvim-treesitter",
  --   "nvim-tree/nvim-web-devicons"
  -- },
  -- config = function()
  --   require("lspsaga").setup({
  --     -- uses winbar - nvim-navic is more flexible and should work with lualine
  --     symbol_in_winbar = {
  --       enable = true,
  --       separator = '  ',
  --       show_file = true,
  --       hide_keyword = true,
  --       folder_level = 0,
  --     },
  --
  --     lightbulb = { enable = false },
  --     ui = {
  --       code_action = ""
  --     },
  --   })
  -- end,
}
